import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Shared-Components/Navbar";
import Banner from "./Shared-Components/Banner";
import BookProvider, { BookContext } from "./Context/BookContext";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Footer from "./Shared-Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Book Vibe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en" data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <BookProvider>


        <Navbar/>
        
        <div className="flex-grow">
          {children}
        </div>
        <Footer/>
        
        <ToastContainer position="top-right" autoClose={3000} />
        </BookProvider>
        </body>
    </html>
  );
}
